version: '3'
services:
  nestjs-server:
    build:
      context: ./backend-image
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: nest-api
  vue-frontend:
    build:
      context: ./frontend-image
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-frontend